apiVersion: v2
name: cronjob
description: A Helm chart for Kubernetes cronjob
type: application

version: 0.10.9

keywords:
  - cronjob

maintainers:
  - name: juri
    url: https://github.com/juriku/helm-charts

dependencies:
  - name: base
    version: ~0
    repository: file://../base
