apiVersion: v2
name: app
description: A Helm chart for Kubernetes Deployment
type: application

version: 0.18.5

keywords:
  - deployment
  - StatefulSet
  - configmap
  - secret
  - HorizontalPodAutoscaler
  - hpa
  - VerticalPodAutoscaler
  - podDisruptionBudget
  - service
  - ingress
  - analysisTemplate
  - rbac

maintainers:
  - name: juri
    url: https://github.com/juriku/helm-charts

dependencies:
  - name: base
    version: ~0
    repository: file://../base

kubeVersion: ">=1.23.0-0"

home: https://github.com/juriku/helm-charts

sources:
  - https://github.com/juriku/helm-charts

annotations:
  org.opencontainers.image.source: https://github.com/juriku/helm-charts
