{{- if .Values.server.additionalApplications }}
{{- $appDefaults := .Values.server.additionalApplicationsDefaults -}}
apiVersion: v1
kind: List
items:
{{- range $appValuesOrig := .Values.server.additionalApplications }}
{{- $appValues := mergeOverwrite (dict) (deepCopy $appDefaults) $appValuesOrig }}
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      {{- if $appValues.additionalAnnotations }}
      annotations:
      {{- range $key, $value := $appValues.additionalAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      {{- if $appValues.additionalLabels }}
      labels:
{{- toYaml $appValues.additionalLabels | nindent 8 }}
      {{- end }}
      name: {{ .name }}
      {{- if $appValues.namespace }}
      namespace: {{ $appValues.namespace }}
      {{- end }}
      {{- if $appValues.finalizers }}
      finalizers:
{{- toYaml $appValues.finalizers | nindent 8 }}
      {{- end }}
    spec:
      project: {{ tpl $appValues.project $ }}
      source:
{{- toYaml $appValues.source | nindent 8 }}
      destination:
{{- toYaml $appValues.destination | nindent 8 }}
      {{- if $appValues.syncPolicy }}
      syncPolicy:
{{- toYaml $appValues.syncPolicy | nindent 8 }}
      {{- end }}
      {{- if $appValues.ignoreDifferences }}
      ignoreDifferences:
{{- toYaml $appValues.ignoreDifferences | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}