apiVersion: v2
name: ingress
description: A Helm chart for Kubernetes ingress
type: application
version: 0.2.0

keywords:
  - ingress

maintainers:
  - name: juri
    url: https://github.com/juriku/helm-charts

dependencies:
  - name: base
    repository: https://juriku.github.io/helm-charts
    version: 0.1.0