apiVersion: v2
name: base
description: A Helm chart for Kubernetes with helm named templates
type: library

version: 0.10.7

keywords:
  - deployment
  - configmap
  - secret
  - HorizontalPodAutoscaler
  - hpa
  - VerticalPodAutoscaler
  - podDisruptionBudget
  - service
  - ingress
  - storageClass
  - pvc

maintainers:
  - name: juri
    url: https://github.com/juriku/helm-charts
