apiVersion: v2
name: base
description: A Helm chart for Kubernetes with helm named templates
type: library

version: 0.18.5

keywords:
  - deployment
  - configmap
  - secret
  - HorizontalPodAutoscaler
  - hpa
  - VerticalPodAutoscaler
  - podDisruptionBudget
  - service
  - ingress
  - storageClass
  - pvc

maintainers:
  - name: juri
    url: https://github.com/juriku/helm-charts

kubeVersion: ">=1.23.0-0"

home: https://github.com/juriku/helm-charts

sources:
  - https://github.com/juriku/helm-charts

annotations:
  org.opencontainers.image.source: https://github.com/juriku/helm-charts
