apiVersion: v2
name: base
description: A Helm chart for Kubernetes with helm named templates
type: library

version: 0.18.3

keywords:
  - deployment
  - configmap
  - secret
  - HorizontalPodAutoscaler
  - hpa
  - VerticalPodAutoscaler
  - podDisruptionBudget
  - service
  - ingress
  - storageClass
  - pvc

maintainers:
  - name: juri
    url: https://github.com/ferodrinks/helm-charts

annotations:
  org.opencontainers.image.source: https://github.com/ferodrinks/helm-charts
