apiVersion: v2
name: base
description: A Helm chart for Kubernetes with helm named templates 
type: library

version: 0.2.0

keywords:
  - deployment
  - configmap
  - secret
  - HorizontalPodAutoscaler
  - hpa
  - VerticalPodAutoscaler
  - podDisruptionBudget
  - service
  - ingress
  - storageClass

maintainers:
  - name: juri
    url: https://github.com/juriku/helm-charts