apiVersion: v2
name: argo-applications
description: A Helm chart for Kubernetes argo applications
type: application

version: 0.18.5

keywords:
  - argocd
  - workflows

maintainers:
  - name: juri
    url: https://github.com/juriku/helm-charts

kubeVersion: ">=1.23.0-0"

home: https://github.com/juriku/helm-charts

sources:
  - https://github.com/juriku/helm-charts

annotations:
  org.opencontainers.image.source: https://github.com/juriku/helm-charts
