apiVersion: v2
name: argo-workflows
description: A Helm chart for Kubernetes argocd workflows
type: application

version: 0.15.0

keywords:
  - argocd
  - workflows

maintainers:
  - name: juri
    url: https://github.com/juriku/helm-charts

dependencies:
  - name: base
    version: ~0
    repository: file://../base