apiVersion: v2
name: job
description: A Helm chart for Kubernetes job
type: application

version: 0.14.0

keywords:
  - job

maintainers:
  - name: juri
    url: https://github.com/juriku/helm-charts

dependencies:
  - name: base
    version: ~0
    repository: file://../base